# Generated by Django 4.1 on 2022-08-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_dirigentes_funcionarios_hinchas_jugadores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hinchas',
            old_name='nuerodesocio',
            new_name='numerodesocio',
        ),
    ]
