# Generated by Django 4.1 on 2022-09-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_rename_nuerodesocio_hinchas_numerodesocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('contactotelefonico', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Chat',
        ),
        migrations.RenameModel(
            old_name='Dirigentes',
            new_name='Nosotros',
        ),
        migrations.RenameModel(
            old_name='Jugadores',
            new_name='Noticias',
        ),
        migrations.RenameModel(
            old_name='Hinchas',
            new_name='Selecciones',
        ),
    ]
