# Generated by Django 4.1 on 2022-09-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_productos_rename_funcionarios_chat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jugadoresSelecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('nacimiento', models.DateField()),
                ('posicion', models.CharField(max_length=30)),
            ],
        ),
    ]
