# Generated by Django 4.1 on 2022-09-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_delete_chat_delete_noticias_delete_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='contactos',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
    ]
