# Generated by Django 4.1 on 2022-10-03 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nosotros',
        ),
        migrations.DeleteModel(
            name='Selecciones',
        ),
        migrations.DeleteModel(
            name='Suscripciones',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
